Changing to more like Narze's style

diff --git a/home/dot_zshrc.tmpl b/home/dot_zshrc.tmpl
--- a/home/dot_zshrc.tmpl
+++ b/home/dot_zshrc.tmpl
@@ -1,114 +1,224 @@
+# Personal Zsh configuration file. It is strongly recommended to keep all
+# shell customization and configuration (including exported environment
+# variables such as PATH) in this file or in files source by it.
+#
+# Documentation: https://github.com/romkatv/zsh4humans/blob/v5/README.md.
 
-# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
-# Initialization code that may require console input (password prompts, [y/n]
-# confirmations, etc.) must go above this block, everything else may go below.
-if [[ -r "$HOME/.cache/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
-  source "$HOME/.cache/p10k-instant-prompt-${(%):-%n}.zsh"
+if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
+  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
 
-# Path to your oh-my-zsh configuration.
-export ZSH=$HOME/.oh-my-zsh
-# if you want to use this, change your non-ascii font to Droid Sans Mono for Awesome
+if [[ -n "${GITHUB_CODESPACE_TOKEN}" ]]; then
+  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
+fi
 
-export ZSH_THEME="powerlevel10k/powerlevel10k"
+export EDITOR="code -w"
+export TERM=xterm-256color
+export LC_ALL=en_US.UTF-8
+export LANG=en_US.UTF-8
+export PATH="$PATH:${HOME}/.local/bin"
 
-# export ZSH_THEME="agnoster"
-POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
+# Chezmoi cached variables
+export CM_computer_name={{ .computer_name }}
+export CM_hostname={{ .hostname }}
 
-# https://github.com/bhilburn/powerlevel9k#customizing-prompt-segments
-# https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt
-POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir node_version vcs)
-POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time)
+# force zsh-you-should-use
+# export YSU_HARDCORE=1
 
-# colorcode test
-# for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"
-POWERLEVEL9K_NODE_VERSION_FOREGROUND='000'
-POWERLEVEL9K_NODE_VERSION_BACKGROUND='072'
-POWERLEVEL9K_SHOW_CHANGESET=true
-#export ZSH_THEME="random"
+# export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
 
-# Set to this to use case-sensitive completion
-export CASE_SENSITIVE="true"
+# History
+# https://unix.stackexchange.com/questions/273861/unlimited-history-in-zsh
+HISTFILE="$HOME/.zsh_history"
+HISTSIZE=10000000
+SAVEHIST=10000000
+setopt BANG_HIST                 # Treat the '!' character specially during expansion.
+setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
+setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
+setopt SHARE_HISTORY             # Share history between all sessions.
+setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
+setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
+setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
+setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
+setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
+setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
+setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
+setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
+setopt HIST_BEEP                 # Beep when accessing nonexistent history.
 
-# disable weekly auto-update checks
-# export DISABLE_AUTO_UPDATE="true"
+ulimit -n 8192
 
-# disable colors in ls
-# export DISABLE_LS_COLORS="true"
+# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs rbenv rspec_stats newline)
+# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator ip background_jobs history time)
 
-# disable autosetting terminal title.
-export DISABLE_AUTO_TITLE="true"
+# Prefer using emacs mode for zsh
+bindkey -e
 
-# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
-# Example format: plugins=(rails git textmate ruby lighthouse)
-plugins=(
-  colorize
-  compleat
-  cp
-  dirpersist
-  git
-  gulp
-  history
-  z
-  zsh-autosuggestions
-  zsh-syntax-highlighting
-)
+# Periodic auto-update on Zsh startup: 'ask' or 'no'.
+# You can manually run `z4h update` to update everything.
+zstyle ':z4h:' auto-update      'no'
+# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
+zstyle ':z4h:' auto-update-days '28'
 
-source $ZSH/oh-my-zsh.sh
-source <(kubectl completion zsh)
+# Start tmux if not already in tmux.
+# zstyle ':z4h:' start-tmux       command tmux -u new -A -D -t z4h
 
-test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
+# Move prompt to the bottom when zsh starts and on Ctrl+L.
+zstyle ':z4h:' prompt-at-bottom 'yes'
 
-# source /usr/local/bin/n
+# Keyboard type: 'mac' or 'pc'.
+zstyle ':z4h:bindkey' keyboard  'mac'
 
-autoload -U add-zsh-hook
-# load-nvmrc() {
-#   if [[ -f .nvmrc && -r .nvmrc ]]; then
-#     nvm use &> /dev/null
-#   elif [[ $(nvm version) != $(nvm version default)  ]]; then
-#     nvm use default &> /dev/null
-#   fi
-# }
-# add-zsh-hook chpwd
-# load-nvmrc
+# Right-arrow key accepts one character ('partial-accept') from
+# command autosuggestions or the whole thing ('accept')?
+zstyle ':z4h:autosuggestions' forward-char 'accept'
 
-# Customize to your needs...
-unsetopt correct
+# Recursively traverse directories when TAB-completing files.
+zstyle ':z4h:fzf-complete' recurse-dirs 'yes'
 
-# run fortune on new terminal :)
-# fortune
-# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
-# This loads nvm bash_completion
-# [ -d "/usr/local/opt/python@2/bin" ] && export PATH="/usr/local/opt/python@2/bin:$PATH"
+# Enable direnv to automatically source .envrc files.
+zstyle ':z4h:direnv'         enable 'yes'
+# Show "loading" and "unloading" notifications from direnv.
+zstyle ':z4h:direnv:success' notify 'yes'
 
-export PATH="$PATH:$(yarn global bin)"
+# Enable ('yes') or disable ('no') automatic teleportation of z4h over
+# ssh when connecting to these hosts.
+zstyle ':z4h:ssh:example-hostname1'   enable 'yes'
+zstyle ':z4h:ssh:*.example-hostname2' enable 'no'
+# The default value if none of the overrides above match the hostname.
+zstyle ':z4h:ssh:*'                   enable 'no'
 
-# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
-# export PATH="$PATH:$HOME/.rvm/bin"
-export PATH="/usr/local/opt/libxml2/bin:$PATH"
+# Send these files over to the remote host when connecting over ssh to the
+# enabled hosts.
+zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'
 
-# N setup
-# export N_PREFIX=$HOME/.n
-# export PATH=$N_PREFIX/bin:$PATH
+# Clone additional Git repositories from GitHub.
+#
+# This doesn't do anything apart from cloning the repository and keeping it
+# up-to-date. Cloned files can be used after `z4h init`. This is just an
+# example. If you don't plan to use Oh My Zsh, delete this line.
+# z4h install ohmyzsh/ohmyzsh || return
+z4h install romkatv/zsh-prompt-benchmark || return
+z4h install mollifier/cd-gitroot || return
+z4h install olets/zsh-abbr || return
 
-# Add Homebrew's executable directory to the front of the PATH
-export PATH=/usr/local/bin:$PATH
+# Install or update core components (fzf, zsh-autosuggestions, etc.) and
+# initialize Zsh. After this point console I/O is unavailable until Zsh
+# is fully initialized. Everything that requires user interaction or can
+# perform network I/O must be done above. Everything else is best done below.
+z4h init || return
 
-export KUBECONFIG="/Users/davidpanzarella/rupie-prod-cluster.yaml"
-alias k=kubectl
-complete -F __start_kubectl k
+# Extend PATH.
+path=(~/bin $path)
 
-eval "$(pyenv init -)"
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/bin:$PATH"
+# Export environment variables.
+export GPG_TTY=$TTY
 
+# Source additional local files if they exist.
+z4h source ~/.env.zsh
 
-# direnv
-which direnv >/dev/null && eval "$(direnv hook zsh)"
+# Use additional Git repositories pulled in with `z4h install`.
+#
+# This is just an example that you should delete. It does nothing useful.
+# z4h source ohmyzsh/ohmyzsh/lib/diagnostics.zsh  # source an individual file
+# z4h load   ohmyzsh/ohmyzsh/plugins/emoji-clock  # load a plugin
+z4h load   romkatv/zsh-prompt-benchmark  # load a plugin
+z4h load   mollifier/cd-gitroot
+z4h load   olets/zsh-abbr
 
-{{- if eq .chezmoi.os "darwin" }}
-export HOMEBREW_NO_AUTO_UPDATE=1
+# Define key bindings.
+z4h bindkey undo Ctrl+/  # undo the last command line change
+z4h bindkey redo Alt+/   # redo the last undone command line change
+
+z4h bindkey z4h-cd-back    Shift+Left   # cd into the previous directory
+z4h bindkey z4h-cd-forward Shift+Right  # cd into the next directory
+z4h bindkey z4h-cd-up      Shift+Up     # cd into the parent directory
+z4h bindkey z4h-cd-down    Shift+Down   # cd into a child directory
+
+# Autoload functions.
+autoload -Uz zmv
+
+# Define functions and completions.
+function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
+compdef _directories md
+
+# Define named directories: ~w <=> Windows home directory on WSL.
+[[ -z $z4h_win_home ]] || hash -d w=$z4h_win_home
+
+# Define aliases.
+alias tree='tree -a -I .git'
+
+# Add flags to existing aliases.
+alias ls="${aliases[ls]:-ls} -A"
+
+# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
+setopt glob_dots     # no special treatment for file names with a leading dot
+setopt no_auto_menu  # require an extra TAB press to open the completion menu
+
+{{ if (eq .chezmoi.os "darwin" ) -}}
+# Mac specific config
+if [[ "$(uname -m)" == "arm64" ]]; then
+  # 3. x86 brew bin
+  if [ -f /usr/local/bin/brew ]; then
+    eval $(/usr/local/bin/brew shellenv)
+  fi
+
+  # 2. arm64 brew
+  if [ -f /opt/homebrew/bin/brew ]; then
+    eval $(/opt/homebrew/bin/brew shellenv)
+  fi
+else
+  # 3. arm64 brew
+  if [ -f /opt/homebrew/bin/brew ]; then
+    eval $(/opt/homebrew/bin/brew shellenv)
+  fi
+
+  # 2. x86 brew bin
+  if [ -f /usr/local/bin/brew ]; then
+    eval $(/usr/local/bin/brew shellenv)
+  fi
+fi
+
+# 1. user brew
+if [ -f ~/homebrew/bin/brew ]; then
+  eval $(~/homebrew/bin/brew shellenv)
+fi
 {{- end }}
 
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+# Cleanup duplicated PATHs (mostly from shellenv evals above)
+PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
+
+if [ -f "$HOME/.zshrc.local" ]; then
+  source "$HOME/.zshrc.local"
+fi
+
+# NixOS
+if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
+  . ~/.nix-profile/etc/profile.d/nix.sh;
+fi
+
+# Zoxide : prompt hook mode
+if command -v zoxide &> /dev/null; then
+  eval "$(zoxide init zsh --hook prompt)"
+fi
+
+z4h source $HOME/.config/zsh/config/00_aliases.zsh
+z4h source $HOME/.config/zsh/config/10_options.zsh
+z4h source $HOME/.config/zsh/config/20_functions.zsh
+
+z4h source $HOME/.asdf/asdf.sh
+
+if [ -d "$HOME/.asdf/plugins/direnv" ]; then
+  eval "$(asdf exec direnv hook zsh)"
+  direnv() { asdf exec direnv "$@"; }
+fi
+
+# Timing App Terminal Support
+if [ $ITERM_SESSION_ID ]; then
+  DISABLE_AUTO_TITLE="true"
+  echo -ne "\033]0; @ ${HOST%%.*} : ${PWD/#$HOME/~} \007"
+fi
+
+precmd() {
+  echo -ne "\033]0; @ ${HOST%%.*} : ${PWD/#$HOME/~} \007"
+}
